### PR TITLE
Refactor Internal Setter smell in Amount class

### PR DESCRIPTION
**Pull request by emaiannone**
Hi, I'm Emanuele Iannone, a master student at University of Salerno.
Since my bachelor's thesis I have been working on a **code smell refactoring plugin** called *aDoctor*, which is able to identify and fix energy-related problems in Android apps.
I launched it on your project, finding different instances of code smells. I chose one of them and let the plugin automatically fix it.
In this case I chose Internal Setter, that is present when non static method calls a setter method of an instance variable instead of directly changing its value. These kind of smell may have a non trivial impact on energy consumption, as shown in this paper: `https://www.sciencedirect.com/science/article/pii/S0950584918301678`.
Besides, this kind of refactoring does not impact on the functionalities of your app, so it is totally safe. Let me know if you are interested in this refactoring proposal.

### CODE REVIEW

**Comment by ubmarco** [comment]
I'd say this changes the behavior of the program, because `this` refers to the outer class while the method populates the `clone`.

**Comment by pokulo** [comment]
@ubmarco right. didn't that.

**Comment by koelleChristian** [comment]
@emaiannone Thanks for your work. However, the proposed change changes the behavior of the method and therefore I regard it as a false positive alert of your software and will not apply it to the sources.

**Comment by emaiannone** [comment]
Thank your for your feedbacks, The tool is still under development, but I'll fix this problem as soon as possible :)

**Pull request closed without merging**
