### PR TITLE
Add spanish translations

### PR DESCRIPTION
**Pull request by rogorido**
Thnaks a lot for your app. I just translate it to Spanish. (I hope everything worked, this is the 1. time I made a pull request...).

### CODE REVIEW

**Comment by rogorido** [comment]
I still have to make the translation for the currencies. I just translated the strings...

**Comment by koelleChristian** [comment]
Merge pull request from rogorido

**Comment by koelleChristian** [comment]
As I said, thanks a lot for your support.
I don't speak Spanish. 

A few issues:

1.) The following values have not been translated.
```
    <string name="fileExportSpendingsHeadingSpendingGlobal">Expenditure</string>
    <string name="fileExportSpendingsHeadingTotalCount">Total payment count</string>
    <string name="report_view_subheading_spendings">Expenditure</string>
    <string name="payment_edit_view_label_travellers_charged">Travelers charged:</string>
```
Is this intentional? It would be very kind of you to check this out.

2.) Various values started with a Character "¿"
I removed that, as it did not appear to be correct.

3.) The arrays.xml file I pulled from you, which holds the currency name translations is identical with the English source version. It might actually be understandable. Let me know if you can provide a translation of that or not.

Regards
Christian

**Comment by rogorido** [comment]
Thanks.

1.) no, this is a small error. I'll make another pull request with the corrections.
2.) unfortunately it was correct... In Spanish there are 2 interrogations signs: ¿...?  (See: https://de.wikipedia.org/wiki/Fragezeichen#Spanische_Besonderheit )
3.) the array.xml file will be translated in the next days... by the way: it is really necessary to have "spanish peseta", etc.? These currencies do not exist anymore...

**Comment by koelleChristian** [comment]
Thanks a 1000 times.

I will integrate this soon.

Would you mind if I quote your name in the release log, i.e. “Added Spanish translation (thanks to Igor Sosa Mayor).”

**Comment by rogorido** [comment]
Yes, you can of course add my name. Thanks. I

**Pull request merged**
